server:
  port: 8888 
spring:
  application:
    name: demo-redis
  zipkin:
    base-url: http://127.0.0.1:9411

spring:
  redis:
    #database: 0 # Redis数据库索引（默认为0）
    #host: 192.168.1.8
    #port: 6379
    #password: 123456
    timeout: 10000 # 连接超时时间（毫秒）  
    max-redirects: 3
#  pool: 
#    max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#    max-idle: 8 # 连接池中的最大空闲连接
#    max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    min-idle: 0 # 连接池中的最小空闲连接
    cluster:
      nodes:
        - redisCluster:7000
        - redisCluster:6999
        - redisCluster:6998
        - redisCluster:6997
        - redisCluster:6996
        - redisCluster:6995