// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/exporttask.proto

package com.jw.platform.pcm.m4910.f010.microservice;

public interface WshExportTaskListTplResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exporttask.WshExportTaskListTplRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string errCode = 1;</code>
   */
  java.lang.String getErrCode();
  /**
   * <code>string errCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getErrCodeBytes();

  /**
   * <code>string errMsg = 2;</code>
   */
  java.lang.String getErrMsg();
  /**
   * <code>string errMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrMsgBytes();

  /**
   * <code>repeated .exporttask.WshExportTpl data = 3;</code>
   */
  java.util.List<com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl> 
      getDataList();
  /**
   * <code>repeated .exporttask.WshExportTpl data = 3;</code>
   */
  com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl getData(int index);
  /**
   * <code>repeated .exporttask.WshExportTpl data = 3;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .exporttask.WshExportTpl data = 3;</code>
   */
  java.util.List<? extends com.jw.platform.pcm.m4910.f010.microservice.WshExportTplOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .exporttask.WshExportTpl data = 3;</code>
   */
  com.jw.platform.pcm.m4910.f010.microservice.WshExportTplOrBuilder getDataOrBuilder(
      int index);
}
