// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/exporttask.proto

package com.jw.platform.pcm.m4910.f010.microservice;

public final class WshExportTaskProto {
  private WshExportTaskProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exporttask_WshExportTpl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exporttask_WshExportTpl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exporttask_WshExportTaskCreateTplReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exporttask_WshExportTaskCreateTplReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exporttask_WshExportTaskCreateTplRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exporttask_WshExportTaskCreateTplRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exporttask_WshExportTaskListTplReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exporttask_WshExportTaskListTplReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exporttask_WshExportTaskListTplRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exporttask_WshExportTaskListTplRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto/exporttask.proto\022\nexporttask\"\274\002\n" +
      "\014WshExportTpl\022\020\n\010etplName\030\001 \001(\t\022\017\n\007etplT" +
      "ag\030\002 \001(\t\0225\n\020etplOutputFormat\030\003 \001(\0162\033.exp" +
      "orttask.WshExportFormat\022\031\n\021etplOutputCol" +
      "umns\030\004 \001(\t\022\020\n\010etplExpr\030\005 \001(\t\022\016\n\006etplId\030\006" +
      " \001(\005\022\025\n\retplExecTimes\030\007 \001(\005\022\027\n\017etplExecO" +
      "kTimes\030\010 \001(\005\022\022\n\netplStatus\030\t \001(\005\022\023\n\013etpl" +
      "Created\030\n \001(\t\022\023\n\013etplUpdated\030\013 \001(\t\022\023\n\013et" +
      "plDeleted\030\014 \001(\t\022\022\n\noperatorId\030\r \001(\005\"\266\001\n\031" +
      "WshExportTaskCreateTplReq\022\020\n\010etplName\030\001 " +
      "\001(\t\022\017\n\007etplTag\030\002 \001(\t\022\020\n\010etplExpr\030\003 \001(\t\022\031" +
      "\n\021etplOutputColumns\030\004 \001(\t\0225\n\020etplOutputF" +
      "ormat\030\005 \001(\0162\033.exporttask.WshExportFormat" +
      "\022\022\n\noperatorId\030\006 \001(\005\"d\n\031WshExportTaskCre" +
      "ateTplRes\022\017\n\007errCode\030\001 \001(\t\022\016\n\006errMsg\030\002 \001" +
      "(\t\022&\n\004data\030\003 \001(\0132\030.exporttask.WshExportT" +
      "pl\"L\n\027WshExportTaskListTplReq\022\016\n\006etplId\030" +
      "\001 \001(\005\022\020\n\010etplName\030\002 \001(\t\022\017\n\007etplTag\030\003 \001(\t" +
      "\"b\n\027WshExportTaskListTplRes\022\017\n\007errCode\030\001" +
      " \001(\t\022\016\n\006errMsg\030\002 \001(\t\022&\n\004data\030\003 \003(\0132\030.exp" +
      "orttask.WshExportTpl*E\n\022WshExportTplStat" +
      "us\022\016\n\nTPL_INITED\020\000\022\016\n\nTPL_NORMAL\020\001\022\017\n\013TP" +
      "L_DELETED\020\t*<\n\017WshExportFormat\022\017\n\013FMT_DE" +
      "FAULT\020\000\022\013\n\007FMT_CSV\020\001\022\013\n\007FMT_XLS\020\0022\300\001\n\nEx" +
      "portTask\022[\n\tCreateTpl\022%.exporttask.WshEx" +
      "portTaskCreateTplReq\032%.exporttask.WshExp" +
      "ortTaskCreateTplRes\"\000\022U\n\007ListTpl\022#.expor" +
      "ttask.WshExportTaskListTplReq\032#.exportta" +
      "sk.WshExportTaskListTplRes\"\000BC\n+com.jw.p" +
      "latform.pcm.m4910.f010.microserviceB\022Wsh" +
      "ExportTaskProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_exporttask_WshExportTpl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_exporttask_WshExportTpl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exporttask_WshExportTpl_descriptor,
        new java.lang.String[] { "EtplName", "EtplTag", "EtplOutputFormat", "EtplOutputColumns", "EtplExpr", "EtplId", "EtplExecTimes", "EtplExecOkTimes", "EtplStatus", "EtplCreated", "EtplUpdated", "EtplDeleted", "OperatorId", });
    internal_static_exporttask_WshExportTaskCreateTplReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_exporttask_WshExportTaskCreateTplReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exporttask_WshExportTaskCreateTplReq_descriptor,
        new java.lang.String[] { "EtplName", "EtplTag", "EtplExpr", "EtplOutputColumns", "EtplOutputFormat", "OperatorId", });
    internal_static_exporttask_WshExportTaskCreateTplRes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_exporttask_WshExportTaskCreateTplRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exporttask_WshExportTaskCreateTplRes_descriptor,
        new java.lang.String[] { "ErrCode", "ErrMsg", "Data", });
    internal_static_exporttask_WshExportTaskListTplReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_exporttask_WshExportTaskListTplReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exporttask_WshExportTaskListTplReq_descriptor,
        new java.lang.String[] { "EtplId", "EtplName", "EtplTag", });
    internal_static_exporttask_WshExportTaskListTplRes_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_exporttask_WshExportTaskListTplRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exporttask_WshExportTaskListTplRes_descriptor,
        new java.lang.String[] { "ErrCode", "ErrMsg", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
