// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/exporttask.proto

package com.jw.platform.pcm.m4910.f010.microservice;

public interface WshExportTaskCreateTplResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exporttask.WshExportTaskCreateTplRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string errCode = 1;</code>
   */
  java.lang.String getErrCode();
  /**
   * <code>string errCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getErrCodeBytes();

  /**
   * <code>string errMsg = 2;</code>
   */
  java.lang.String getErrMsg();
  /**
   * <code>string errMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrMsgBytes();

  /**
   * <code>.exporttask.WshExportTpl data = 3;</code>
   */
  boolean hasData();
  /**
   * <code>.exporttask.WshExportTpl data = 3;</code>
   */
  com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl getData();
  /**
   * <code>.exporttask.WshExportTpl data = 3;</code>
   */
  com.jw.platform.pcm.m4910.f010.microservice.WshExportTplOrBuilder getDataOrBuilder();
}
