// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/exporttask.proto

package com.jw.platform.pcm.m4910.f010.microservice;

public interface WshExportTaskCreateTplReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exporttask.WshExportTaskCreateTplReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string etplName = 1;</code>
   */
  java.lang.String getEtplName();
  /**
   * <code>string etplName = 1;</code>
   */
  com.google.protobuf.ByteString
      getEtplNameBytes();

  /**
   * <code>string etplTag = 2;</code>
   */
  java.lang.String getEtplTag();
  /**
   * <code>string etplTag = 2;</code>
   */
  com.google.protobuf.ByteString
      getEtplTagBytes();

  /**
   * <code>string etplExpr = 3;</code>
   */
  java.lang.String getEtplExpr();
  /**
   * <code>string etplExpr = 3;</code>
   */
  com.google.protobuf.ByteString
      getEtplExprBytes();

  /**
   * <code>string etplOutputColumns = 4;</code>
   */
  java.lang.String getEtplOutputColumns();
  /**
   * <code>string etplOutputColumns = 4;</code>
   */
  com.google.protobuf.ByteString
      getEtplOutputColumnsBytes();

  /**
   * <code>.exporttask.WshExportFormat etplOutputFormat = 5;</code>
   */
  int getEtplOutputFormatValue();
  /**
   * <code>.exporttask.WshExportFormat etplOutputFormat = 5;</code>
   */
  com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat getEtplOutputFormat();

  /**
   * <code>int32 operatorId = 6;</code>
   */
  int getOperatorId();
}
