// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/exporttask.proto

package com.jw.platform.pcm.m4910.f010.microservice;

/**
 * <pre>
 * 枚举类型，必须从0开始，序号可跨越。同一包下不能重名，所以加前缀来区别
 * </pre>
 *
 * Protobuf enum {@code exporttask.WshExportTplStatus}
 */
public enum WshExportTplStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TPL_INITED = 0;</code>
   */
  TPL_INITED(0),
  /**
   * <code>TPL_NORMAL = 1;</code>
   */
  TPL_NORMAL(1),
  /**
   * <code>TPL_DELETED = 9;</code>
   */
  TPL_DELETED(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TPL_INITED = 0;</code>
   */
  public static final int TPL_INITED_VALUE = 0;
  /**
   * <code>TPL_NORMAL = 1;</code>
   */
  public static final int TPL_NORMAL_VALUE = 1;
  /**
   * <code>TPL_DELETED = 9;</code>
   */
  public static final int TPL_DELETED_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static WshExportTplStatus valueOf(int value) {
    return forNumber(value);
  }

  public static WshExportTplStatus forNumber(int value) {
    switch (value) {
      case 0: return TPL_INITED;
      case 1: return TPL_NORMAL;
      case 9: return TPL_DELETED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<WshExportTplStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      WshExportTplStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<WshExportTplStatus>() {
          public WshExportTplStatus findValueByNumber(int number) {
            return WshExportTplStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final WshExportTplStatus[] VALUES = values();

  public static WshExportTplStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private WshExportTplStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:exporttask.WshExportTplStatus)
}

