// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/exporttask.proto

package com.jw.platform.pcm.m4910.f010.microservice;

public interface WshExportTplOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exporttask.WshExportTpl)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string etplName = 1;</code>
   */
  java.lang.String getEtplName();
  /**
   * <code>string etplName = 1;</code>
   */
  com.google.protobuf.ByteString
      getEtplNameBytes();

  /**
   * <code>string etplTag = 2;</code>
   */
  java.lang.String getEtplTag();
  /**
   * <code>string etplTag = 2;</code>
   */
  com.google.protobuf.ByteString
      getEtplTagBytes();

  /**
   * <code>.exporttask.WshExportFormat etplOutputFormat = 3;</code>
   */
  int getEtplOutputFormatValue();
  /**
   * <code>.exporttask.WshExportFormat etplOutputFormat = 3;</code>
   */
  com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat getEtplOutputFormat();

  /**
   * <code>string etplOutputColumns = 4;</code>
   */
  java.lang.String getEtplOutputColumns();
  /**
   * <code>string etplOutputColumns = 4;</code>
   */
  com.google.protobuf.ByteString
      getEtplOutputColumnsBytes();

  /**
   * <code>string etplExpr = 5;</code>
   */
  java.lang.String getEtplExpr();
  /**
   * <code>string etplExpr = 5;</code>
   */
  com.google.protobuf.ByteString
      getEtplExprBytes();

  /**
   * <code>int32 etplId = 6;</code>
   */
  int getEtplId();

  /**
   * <code>int32 etplExecTimes = 7;</code>
   */
  int getEtplExecTimes();

  /**
   * <code>int32 etplExecOkTimes = 8;</code>
   */
  int getEtplExecOkTimes();

  /**
   * <code>int32 etplStatus = 9;</code>
   */
  int getEtplStatus();

  /**
   * <code>string etplCreated = 10;</code>
   */
  java.lang.String getEtplCreated();
  /**
   * <code>string etplCreated = 10;</code>
   */
  com.google.protobuf.ByteString
      getEtplCreatedBytes();

  /**
   * <code>string etplUpdated = 11;</code>
   */
  java.lang.String getEtplUpdated();
  /**
   * <code>string etplUpdated = 11;</code>
   */
  com.google.protobuf.ByteString
      getEtplUpdatedBytes();

  /**
   * <code>string etplDeleted = 12;</code>
   */
  java.lang.String getEtplDeleted();
  /**
   * <code>string etplDeleted = 12;</code>
   */
  com.google.protobuf.ByteString
      getEtplDeletedBytes();

  /**
   * <code>int32 operatorId = 13;</code>
   */
  int getOperatorId();
}
