// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/exporttask.proto

package com.jw.platform.pcm.m4910.f010.microservice;

/**
 * Protobuf type {@code exporttask.WshExportTaskCreateTplReq}
 */
public  final class WshExportTaskCreateTplReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:exporttask.WshExportTaskCreateTplReq)
    WshExportTaskCreateTplReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WshExportTaskCreateTplReq.newBuilder() to construct.
  private WshExportTaskCreateTplReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WshExportTaskCreateTplReq() {
    etplName_ = "";
    etplTag_ = "";
    etplExpr_ = "";
    etplOutputColumns_ = "";
    etplOutputFormat_ = 0;
    operatorId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WshExportTaskCreateTplReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            etplName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            etplTag_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            etplExpr_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            etplOutputColumns_ = s;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            etplOutputFormat_ = rawValue;
            break;
          }
          case 48: {

            operatorId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTaskCreateTplReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTaskCreateTplReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq.class, com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq.Builder.class);
  }

  public static final int ETPLNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object etplName_;
  /**
   * <code>string etplName = 1;</code>
   */
  public java.lang.String getEtplName() {
    java.lang.Object ref = etplName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      etplName_ = s;
      return s;
    }
  }
  /**
   * <code>string etplName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEtplNameBytes() {
    java.lang.Object ref = etplName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      etplName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ETPLTAG_FIELD_NUMBER = 2;
  private volatile java.lang.Object etplTag_;
  /**
   * <code>string etplTag = 2;</code>
   */
  public java.lang.String getEtplTag() {
    java.lang.Object ref = etplTag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      etplTag_ = s;
      return s;
    }
  }
  /**
   * <code>string etplTag = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEtplTagBytes() {
    java.lang.Object ref = etplTag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      etplTag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ETPLEXPR_FIELD_NUMBER = 3;
  private volatile java.lang.Object etplExpr_;
  /**
   * <code>string etplExpr = 3;</code>
   */
  public java.lang.String getEtplExpr() {
    java.lang.Object ref = etplExpr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      etplExpr_ = s;
      return s;
    }
  }
  /**
   * <code>string etplExpr = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEtplExprBytes() {
    java.lang.Object ref = etplExpr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      etplExpr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ETPLOUTPUTCOLUMNS_FIELD_NUMBER = 4;
  private volatile java.lang.Object etplOutputColumns_;
  /**
   * <code>string etplOutputColumns = 4;</code>
   */
  public java.lang.String getEtplOutputColumns() {
    java.lang.Object ref = etplOutputColumns_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      etplOutputColumns_ = s;
      return s;
    }
  }
  /**
   * <code>string etplOutputColumns = 4;</code>
   */
  public com.google.protobuf.ByteString
      getEtplOutputColumnsBytes() {
    java.lang.Object ref = etplOutputColumns_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      etplOutputColumns_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ETPLOUTPUTFORMAT_FIELD_NUMBER = 5;
  private int etplOutputFormat_;
  /**
   * <code>.exporttask.WshExportFormat etplOutputFormat = 5;</code>
   */
  public int getEtplOutputFormatValue() {
    return etplOutputFormat_;
  }
  /**
   * <code>.exporttask.WshExportFormat etplOutputFormat = 5;</code>
   */
  public com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat getEtplOutputFormat() {
    @SuppressWarnings("deprecation")
    com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat result = com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat.valueOf(etplOutputFormat_);
    return result == null ? com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat.UNRECOGNIZED : result;
  }

  public static final int OPERATORID_FIELD_NUMBER = 6;
  private int operatorId_;
  /**
   * <code>int32 operatorId = 6;</code>
   */
  public int getOperatorId() {
    return operatorId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEtplNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, etplName_);
    }
    if (!getEtplTagBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, etplTag_);
    }
    if (!getEtplExprBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, etplExpr_);
    }
    if (!getEtplOutputColumnsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, etplOutputColumns_);
    }
    if (etplOutputFormat_ != com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat.FMT_DEFAULT.getNumber()) {
      output.writeEnum(5, etplOutputFormat_);
    }
    if (operatorId_ != 0) {
      output.writeInt32(6, operatorId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEtplNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, etplName_);
    }
    if (!getEtplTagBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, etplTag_);
    }
    if (!getEtplExprBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, etplExpr_);
    }
    if (!getEtplOutputColumnsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, etplOutputColumns_);
    }
    if (etplOutputFormat_ != com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat.FMT_DEFAULT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, etplOutputFormat_);
    }
    if (operatorId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, operatorId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq)) {
      return super.equals(obj);
    }
    com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq other = (com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq) obj;

    boolean result = true;
    result = result && getEtplName()
        .equals(other.getEtplName());
    result = result && getEtplTag()
        .equals(other.getEtplTag());
    result = result && getEtplExpr()
        .equals(other.getEtplExpr());
    result = result && getEtplOutputColumns()
        .equals(other.getEtplOutputColumns());
    result = result && etplOutputFormat_ == other.etplOutputFormat_;
    result = result && (getOperatorId()
        == other.getOperatorId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ETPLNAME_FIELD_NUMBER;
    hash = (53 * hash) + getEtplName().hashCode();
    hash = (37 * hash) + ETPLTAG_FIELD_NUMBER;
    hash = (53 * hash) + getEtplTag().hashCode();
    hash = (37 * hash) + ETPLEXPR_FIELD_NUMBER;
    hash = (53 * hash) + getEtplExpr().hashCode();
    hash = (37 * hash) + ETPLOUTPUTCOLUMNS_FIELD_NUMBER;
    hash = (53 * hash) + getEtplOutputColumns().hashCode();
    hash = (37 * hash) + ETPLOUTPUTFORMAT_FIELD_NUMBER;
    hash = (53 * hash) + etplOutputFormat_;
    hash = (37 * hash) + OPERATORID_FIELD_NUMBER;
    hash = (53 * hash) + getOperatorId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code exporttask.WshExportTaskCreateTplReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exporttask.WshExportTaskCreateTplReq)
      com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTaskCreateTplReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTaskCreateTplReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq.class, com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq.Builder.class);
    }

    // Construct using com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      etplName_ = "";

      etplTag_ = "";

      etplExpr_ = "";

      etplOutputColumns_ = "";

      etplOutputFormat_ = 0;

      operatorId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTaskCreateTplReq_descriptor;
    }

    @java.lang.Override
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq getDefaultInstanceForType() {
      return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq build() {
      com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq buildPartial() {
      com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq result = new com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq(this);
      result.etplName_ = etplName_;
      result.etplTag_ = etplTag_;
      result.etplExpr_ = etplExpr_;
      result.etplOutputColumns_ = etplOutputColumns_;
      result.etplOutputFormat_ = etplOutputFormat_;
      result.operatorId_ = operatorId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq) {
        return mergeFrom((com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq other) {
      if (other == com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq.getDefaultInstance()) return this;
      if (!other.getEtplName().isEmpty()) {
        etplName_ = other.etplName_;
        onChanged();
      }
      if (!other.getEtplTag().isEmpty()) {
        etplTag_ = other.etplTag_;
        onChanged();
      }
      if (!other.getEtplExpr().isEmpty()) {
        etplExpr_ = other.etplExpr_;
        onChanged();
      }
      if (!other.getEtplOutputColumns().isEmpty()) {
        etplOutputColumns_ = other.etplOutputColumns_;
        onChanged();
      }
      if (other.etplOutputFormat_ != 0) {
        setEtplOutputFormatValue(other.getEtplOutputFormatValue());
      }
      if (other.getOperatorId() != 0) {
        setOperatorId(other.getOperatorId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object etplName_ = "";
    /**
     * <code>string etplName = 1;</code>
     */
    public java.lang.String getEtplName() {
      java.lang.Object ref = etplName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        etplName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string etplName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEtplNameBytes() {
      java.lang.Object ref = etplName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        etplName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string etplName = 1;</code>
     */
    public Builder setEtplName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      etplName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string etplName = 1;</code>
     */
    public Builder clearEtplName() {
      
      etplName_ = getDefaultInstance().getEtplName();
      onChanged();
      return this;
    }
    /**
     * <code>string etplName = 1;</code>
     */
    public Builder setEtplNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      etplName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object etplTag_ = "";
    /**
     * <code>string etplTag = 2;</code>
     */
    public java.lang.String getEtplTag() {
      java.lang.Object ref = etplTag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        etplTag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string etplTag = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEtplTagBytes() {
      java.lang.Object ref = etplTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        etplTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string etplTag = 2;</code>
     */
    public Builder setEtplTag(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      etplTag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string etplTag = 2;</code>
     */
    public Builder clearEtplTag() {
      
      etplTag_ = getDefaultInstance().getEtplTag();
      onChanged();
      return this;
    }
    /**
     * <code>string etplTag = 2;</code>
     */
    public Builder setEtplTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      etplTag_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object etplExpr_ = "";
    /**
     * <code>string etplExpr = 3;</code>
     */
    public java.lang.String getEtplExpr() {
      java.lang.Object ref = etplExpr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        etplExpr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string etplExpr = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEtplExprBytes() {
      java.lang.Object ref = etplExpr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        etplExpr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string etplExpr = 3;</code>
     */
    public Builder setEtplExpr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      etplExpr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string etplExpr = 3;</code>
     */
    public Builder clearEtplExpr() {
      
      etplExpr_ = getDefaultInstance().getEtplExpr();
      onChanged();
      return this;
    }
    /**
     * <code>string etplExpr = 3;</code>
     */
    public Builder setEtplExprBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      etplExpr_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object etplOutputColumns_ = "";
    /**
     * <code>string etplOutputColumns = 4;</code>
     */
    public java.lang.String getEtplOutputColumns() {
      java.lang.Object ref = etplOutputColumns_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        etplOutputColumns_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string etplOutputColumns = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEtplOutputColumnsBytes() {
      java.lang.Object ref = etplOutputColumns_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        etplOutputColumns_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string etplOutputColumns = 4;</code>
     */
    public Builder setEtplOutputColumns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      etplOutputColumns_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string etplOutputColumns = 4;</code>
     */
    public Builder clearEtplOutputColumns() {
      
      etplOutputColumns_ = getDefaultInstance().getEtplOutputColumns();
      onChanged();
      return this;
    }
    /**
     * <code>string etplOutputColumns = 4;</code>
     */
    public Builder setEtplOutputColumnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      etplOutputColumns_ = value;
      onChanged();
      return this;
    }

    private int etplOutputFormat_ = 0;
    /**
     * <code>.exporttask.WshExportFormat etplOutputFormat = 5;</code>
     */
    public int getEtplOutputFormatValue() {
      return etplOutputFormat_;
    }
    /**
     * <code>.exporttask.WshExportFormat etplOutputFormat = 5;</code>
     */
    public Builder setEtplOutputFormatValue(int value) {
      etplOutputFormat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.exporttask.WshExportFormat etplOutputFormat = 5;</code>
     */
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat getEtplOutputFormat() {
      @SuppressWarnings("deprecation")
      com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat result = com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat.valueOf(etplOutputFormat_);
      return result == null ? com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat.UNRECOGNIZED : result;
    }
    /**
     * <code>.exporttask.WshExportFormat etplOutputFormat = 5;</code>
     */
    public Builder setEtplOutputFormat(com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      etplOutputFormat_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.exporttask.WshExportFormat etplOutputFormat = 5;</code>
     */
    public Builder clearEtplOutputFormat() {
      
      etplOutputFormat_ = 0;
      onChanged();
      return this;
    }

    private int operatorId_ ;
    /**
     * <code>int32 operatorId = 6;</code>
     */
    public int getOperatorId() {
      return operatorId_;
    }
    /**
     * <code>int32 operatorId = 6;</code>
     */
    public Builder setOperatorId(int value) {
      
      operatorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 operatorId = 6;</code>
     */
    public Builder clearOperatorId() {
      
      operatorId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:exporttask.WshExportTaskCreateTplReq)
  }

  // @@protoc_insertion_point(class_scope:exporttask.WshExportTaskCreateTplReq)
  private static final com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq();
  }

  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WshExportTaskCreateTplReq>
      PARSER = new com.google.protobuf.AbstractParser<WshExportTaskCreateTplReq>() {
    @java.lang.Override
    public WshExportTaskCreateTplReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WshExportTaskCreateTplReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WshExportTaskCreateTplReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WshExportTaskCreateTplReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskCreateTplReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

