// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/exporttask.proto

package com.jw.platform.pcm.m4910.f010.microservice;

/**
 * Protobuf enum {@code exporttask.WshExportFormat}
 */
public enum WshExportFormat
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FMT_DEFAULT = 0;</code>
   */
  FMT_DEFAULT(0),
  /**
   * <code>FMT_CSV = 1;</code>
   */
  FMT_CSV(1),
  /**
   * <code>FMT_XLS = 2;</code>
   */
  FMT_XLS(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>FMT_DEFAULT = 0;</code>
   */
  public static final int FMT_DEFAULT_VALUE = 0;
  /**
   * <code>FMT_CSV = 1;</code>
   */
  public static final int FMT_CSV_VALUE = 1;
  /**
   * <code>FMT_XLS = 2;</code>
   */
  public static final int FMT_XLS_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static WshExportFormat valueOf(int value) {
    return forNumber(value);
  }

  public static WshExportFormat forNumber(int value) {
    switch (value) {
      case 0: return FMT_DEFAULT;
      case 1: return FMT_CSV;
      case 2: return FMT_XLS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<WshExportFormat>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      WshExportFormat> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<WshExportFormat>() {
          public WshExportFormat findValueByNumber(int number) {
            return WshExportFormat.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final WshExportFormat[] VALUES = values();

  public static WshExportFormat valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private WshExportFormat(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:exporttask.WshExportFormat)
}

