// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/exporttask.proto

package com.jw.platform.pcm.m4910.f010.microservice;

/**
 * Protobuf type {@code exporttask.WshExportTpl}
 */
public  final class WshExportTpl extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:exporttask.WshExportTpl)
    WshExportTplOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WshExportTpl.newBuilder() to construct.
  private WshExportTpl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WshExportTpl() {
    etplName_ = "";
    etplTag_ = "";
    etplOutputFormat_ = 0;
    etplOutputColumns_ = "";
    etplExpr_ = "";
    etplId_ = 0;
    etplExecTimes_ = 0;
    etplExecOkTimes_ = 0;
    etplStatus_ = 0;
    etplCreated_ = "";
    etplUpdated_ = "";
    etplDeleted_ = "";
    operatorId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WshExportTpl(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            etplName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            etplTag_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            etplOutputFormat_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            etplOutputColumns_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            etplExpr_ = s;
            break;
          }
          case 48: {

            etplId_ = input.readInt32();
            break;
          }
          case 56: {

            etplExecTimes_ = input.readInt32();
            break;
          }
          case 64: {

            etplExecOkTimes_ = input.readInt32();
            break;
          }
          case 72: {

            etplStatus_ = input.readInt32();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            etplCreated_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            etplUpdated_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            etplDeleted_ = s;
            break;
          }
          case 104: {

            operatorId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTpl_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTpl_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.class, com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.Builder.class);
  }

  public static final int ETPLNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object etplName_;
  /**
   * <code>string etplName = 1;</code>
   */
  public java.lang.String getEtplName() {
    java.lang.Object ref = etplName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      etplName_ = s;
      return s;
    }
  }
  /**
   * <code>string etplName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEtplNameBytes() {
    java.lang.Object ref = etplName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      etplName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ETPLTAG_FIELD_NUMBER = 2;
  private volatile java.lang.Object etplTag_;
  /**
   * <code>string etplTag = 2;</code>
   */
  public java.lang.String getEtplTag() {
    java.lang.Object ref = etplTag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      etplTag_ = s;
      return s;
    }
  }
  /**
   * <code>string etplTag = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEtplTagBytes() {
    java.lang.Object ref = etplTag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      etplTag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ETPLOUTPUTFORMAT_FIELD_NUMBER = 3;
  private int etplOutputFormat_;
  /**
   * <code>.exporttask.WshExportFormat etplOutputFormat = 3;</code>
   */
  public int getEtplOutputFormatValue() {
    return etplOutputFormat_;
  }
  /**
   * <code>.exporttask.WshExportFormat etplOutputFormat = 3;</code>
   */
  public com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat getEtplOutputFormat() {
    @SuppressWarnings("deprecation")
    com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat result = com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat.valueOf(etplOutputFormat_);
    return result == null ? com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat.UNRECOGNIZED : result;
  }

  public static final int ETPLOUTPUTCOLUMNS_FIELD_NUMBER = 4;
  private volatile java.lang.Object etplOutputColumns_;
  /**
   * <code>string etplOutputColumns = 4;</code>
   */
  public java.lang.String getEtplOutputColumns() {
    java.lang.Object ref = etplOutputColumns_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      etplOutputColumns_ = s;
      return s;
    }
  }
  /**
   * <code>string etplOutputColumns = 4;</code>
   */
  public com.google.protobuf.ByteString
      getEtplOutputColumnsBytes() {
    java.lang.Object ref = etplOutputColumns_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      etplOutputColumns_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ETPLEXPR_FIELD_NUMBER = 5;
  private volatile java.lang.Object etplExpr_;
  /**
   * <code>string etplExpr = 5;</code>
   */
  public java.lang.String getEtplExpr() {
    java.lang.Object ref = etplExpr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      etplExpr_ = s;
      return s;
    }
  }
  /**
   * <code>string etplExpr = 5;</code>
   */
  public com.google.protobuf.ByteString
      getEtplExprBytes() {
    java.lang.Object ref = etplExpr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      etplExpr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ETPLID_FIELD_NUMBER = 6;
  private int etplId_;
  /**
   * <code>int32 etplId = 6;</code>
   */
  public int getEtplId() {
    return etplId_;
  }

  public static final int ETPLEXECTIMES_FIELD_NUMBER = 7;
  private int etplExecTimes_;
  /**
   * <code>int32 etplExecTimes = 7;</code>
   */
  public int getEtplExecTimes() {
    return etplExecTimes_;
  }

  public static final int ETPLEXECOKTIMES_FIELD_NUMBER = 8;
  private int etplExecOkTimes_;
  /**
   * <code>int32 etplExecOkTimes = 8;</code>
   */
  public int getEtplExecOkTimes() {
    return etplExecOkTimes_;
  }

  public static final int ETPLSTATUS_FIELD_NUMBER = 9;
  private int etplStatus_;
  /**
   * <code>int32 etplStatus = 9;</code>
   */
  public int getEtplStatus() {
    return etplStatus_;
  }

  public static final int ETPLCREATED_FIELD_NUMBER = 10;
  private volatile java.lang.Object etplCreated_;
  /**
   * <code>string etplCreated = 10;</code>
   */
  public java.lang.String getEtplCreated() {
    java.lang.Object ref = etplCreated_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      etplCreated_ = s;
      return s;
    }
  }
  /**
   * <code>string etplCreated = 10;</code>
   */
  public com.google.protobuf.ByteString
      getEtplCreatedBytes() {
    java.lang.Object ref = etplCreated_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      etplCreated_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ETPLUPDATED_FIELD_NUMBER = 11;
  private volatile java.lang.Object etplUpdated_;
  /**
   * <code>string etplUpdated = 11;</code>
   */
  public java.lang.String getEtplUpdated() {
    java.lang.Object ref = etplUpdated_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      etplUpdated_ = s;
      return s;
    }
  }
  /**
   * <code>string etplUpdated = 11;</code>
   */
  public com.google.protobuf.ByteString
      getEtplUpdatedBytes() {
    java.lang.Object ref = etplUpdated_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      etplUpdated_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ETPLDELETED_FIELD_NUMBER = 12;
  private volatile java.lang.Object etplDeleted_;
  /**
   * <code>string etplDeleted = 12;</code>
   */
  public java.lang.String getEtplDeleted() {
    java.lang.Object ref = etplDeleted_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      etplDeleted_ = s;
      return s;
    }
  }
  /**
   * <code>string etplDeleted = 12;</code>
   */
  public com.google.protobuf.ByteString
      getEtplDeletedBytes() {
    java.lang.Object ref = etplDeleted_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      etplDeleted_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATORID_FIELD_NUMBER = 13;
  private int operatorId_;
  /**
   * <code>int32 operatorId = 13;</code>
   */
  public int getOperatorId() {
    return operatorId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEtplNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, etplName_);
    }
    if (!getEtplTagBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, etplTag_);
    }
    if (etplOutputFormat_ != com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat.FMT_DEFAULT.getNumber()) {
      output.writeEnum(3, etplOutputFormat_);
    }
    if (!getEtplOutputColumnsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, etplOutputColumns_);
    }
    if (!getEtplExprBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, etplExpr_);
    }
    if (etplId_ != 0) {
      output.writeInt32(6, etplId_);
    }
    if (etplExecTimes_ != 0) {
      output.writeInt32(7, etplExecTimes_);
    }
    if (etplExecOkTimes_ != 0) {
      output.writeInt32(8, etplExecOkTimes_);
    }
    if (etplStatus_ != 0) {
      output.writeInt32(9, etplStatus_);
    }
    if (!getEtplCreatedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, etplCreated_);
    }
    if (!getEtplUpdatedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, etplUpdated_);
    }
    if (!getEtplDeletedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, etplDeleted_);
    }
    if (operatorId_ != 0) {
      output.writeInt32(13, operatorId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEtplNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, etplName_);
    }
    if (!getEtplTagBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, etplTag_);
    }
    if (etplOutputFormat_ != com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat.FMT_DEFAULT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, etplOutputFormat_);
    }
    if (!getEtplOutputColumnsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, etplOutputColumns_);
    }
    if (!getEtplExprBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, etplExpr_);
    }
    if (etplId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, etplId_);
    }
    if (etplExecTimes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, etplExecTimes_);
    }
    if (etplExecOkTimes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, etplExecOkTimes_);
    }
    if (etplStatus_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, etplStatus_);
    }
    if (!getEtplCreatedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, etplCreated_);
    }
    if (!getEtplUpdatedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, etplUpdated_);
    }
    if (!getEtplDeletedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, etplDeleted_);
    }
    if (operatorId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, operatorId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl)) {
      return super.equals(obj);
    }
    com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl other = (com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl) obj;

    boolean result = true;
    result = result && getEtplName()
        .equals(other.getEtplName());
    result = result && getEtplTag()
        .equals(other.getEtplTag());
    result = result && etplOutputFormat_ == other.etplOutputFormat_;
    result = result && getEtplOutputColumns()
        .equals(other.getEtplOutputColumns());
    result = result && getEtplExpr()
        .equals(other.getEtplExpr());
    result = result && (getEtplId()
        == other.getEtplId());
    result = result && (getEtplExecTimes()
        == other.getEtplExecTimes());
    result = result && (getEtplExecOkTimes()
        == other.getEtplExecOkTimes());
    result = result && (getEtplStatus()
        == other.getEtplStatus());
    result = result && getEtplCreated()
        .equals(other.getEtplCreated());
    result = result && getEtplUpdated()
        .equals(other.getEtplUpdated());
    result = result && getEtplDeleted()
        .equals(other.getEtplDeleted());
    result = result && (getOperatorId()
        == other.getOperatorId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ETPLNAME_FIELD_NUMBER;
    hash = (53 * hash) + getEtplName().hashCode();
    hash = (37 * hash) + ETPLTAG_FIELD_NUMBER;
    hash = (53 * hash) + getEtplTag().hashCode();
    hash = (37 * hash) + ETPLOUTPUTFORMAT_FIELD_NUMBER;
    hash = (53 * hash) + etplOutputFormat_;
    hash = (37 * hash) + ETPLOUTPUTCOLUMNS_FIELD_NUMBER;
    hash = (53 * hash) + getEtplOutputColumns().hashCode();
    hash = (37 * hash) + ETPLEXPR_FIELD_NUMBER;
    hash = (53 * hash) + getEtplExpr().hashCode();
    hash = (37 * hash) + ETPLID_FIELD_NUMBER;
    hash = (53 * hash) + getEtplId();
    hash = (37 * hash) + ETPLEXECTIMES_FIELD_NUMBER;
    hash = (53 * hash) + getEtplExecTimes();
    hash = (37 * hash) + ETPLEXECOKTIMES_FIELD_NUMBER;
    hash = (53 * hash) + getEtplExecOkTimes();
    hash = (37 * hash) + ETPLSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getEtplStatus();
    hash = (37 * hash) + ETPLCREATED_FIELD_NUMBER;
    hash = (53 * hash) + getEtplCreated().hashCode();
    hash = (37 * hash) + ETPLUPDATED_FIELD_NUMBER;
    hash = (53 * hash) + getEtplUpdated().hashCode();
    hash = (37 * hash) + ETPLDELETED_FIELD_NUMBER;
    hash = (53 * hash) + getEtplDeleted().hashCode();
    hash = (37 * hash) + OPERATORID_FIELD_NUMBER;
    hash = (53 * hash) + getOperatorId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code exporttask.WshExportTpl}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exporttask.WshExportTpl)
      com.jw.platform.pcm.m4910.f010.microservice.WshExportTplOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTpl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTpl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.class, com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.Builder.class);
    }

    // Construct using com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      etplName_ = "";

      etplTag_ = "";

      etplOutputFormat_ = 0;

      etplOutputColumns_ = "";

      etplExpr_ = "";

      etplId_ = 0;

      etplExecTimes_ = 0;

      etplExecOkTimes_ = 0;

      etplStatus_ = 0;

      etplCreated_ = "";

      etplUpdated_ = "";

      etplDeleted_ = "";

      operatorId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTpl_descriptor;
    }

    @java.lang.Override
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl getDefaultInstanceForType() {
      return com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.getDefaultInstance();
    }

    @java.lang.Override
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl build() {
      com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl buildPartial() {
      com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl result = new com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl(this);
      result.etplName_ = etplName_;
      result.etplTag_ = etplTag_;
      result.etplOutputFormat_ = etplOutputFormat_;
      result.etplOutputColumns_ = etplOutputColumns_;
      result.etplExpr_ = etplExpr_;
      result.etplId_ = etplId_;
      result.etplExecTimes_ = etplExecTimes_;
      result.etplExecOkTimes_ = etplExecOkTimes_;
      result.etplStatus_ = etplStatus_;
      result.etplCreated_ = etplCreated_;
      result.etplUpdated_ = etplUpdated_;
      result.etplDeleted_ = etplDeleted_;
      result.operatorId_ = operatorId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl) {
        return mergeFrom((com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl other) {
      if (other == com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.getDefaultInstance()) return this;
      if (!other.getEtplName().isEmpty()) {
        etplName_ = other.etplName_;
        onChanged();
      }
      if (!other.getEtplTag().isEmpty()) {
        etplTag_ = other.etplTag_;
        onChanged();
      }
      if (other.etplOutputFormat_ != 0) {
        setEtplOutputFormatValue(other.getEtplOutputFormatValue());
      }
      if (!other.getEtplOutputColumns().isEmpty()) {
        etplOutputColumns_ = other.etplOutputColumns_;
        onChanged();
      }
      if (!other.getEtplExpr().isEmpty()) {
        etplExpr_ = other.etplExpr_;
        onChanged();
      }
      if (other.getEtplId() != 0) {
        setEtplId(other.getEtplId());
      }
      if (other.getEtplExecTimes() != 0) {
        setEtplExecTimes(other.getEtplExecTimes());
      }
      if (other.getEtplExecOkTimes() != 0) {
        setEtplExecOkTimes(other.getEtplExecOkTimes());
      }
      if (other.getEtplStatus() != 0) {
        setEtplStatus(other.getEtplStatus());
      }
      if (!other.getEtplCreated().isEmpty()) {
        etplCreated_ = other.etplCreated_;
        onChanged();
      }
      if (!other.getEtplUpdated().isEmpty()) {
        etplUpdated_ = other.etplUpdated_;
        onChanged();
      }
      if (!other.getEtplDeleted().isEmpty()) {
        etplDeleted_ = other.etplDeleted_;
        onChanged();
      }
      if (other.getOperatorId() != 0) {
        setOperatorId(other.getOperatorId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object etplName_ = "";
    /**
     * <code>string etplName = 1;</code>
     */
    public java.lang.String getEtplName() {
      java.lang.Object ref = etplName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        etplName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string etplName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEtplNameBytes() {
      java.lang.Object ref = etplName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        etplName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string etplName = 1;</code>
     */
    public Builder setEtplName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      etplName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string etplName = 1;</code>
     */
    public Builder clearEtplName() {
      
      etplName_ = getDefaultInstance().getEtplName();
      onChanged();
      return this;
    }
    /**
     * <code>string etplName = 1;</code>
     */
    public Builder setEtplNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      etplName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object etplTag_ = "";
    /**
     * <code>string etplTag = 2;</code>
     */
    public java.lang.String getEtplTag() {
      java.lang.Object ref = etplTag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        etplTag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string etplTag = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEtplTagBytes() {
      java.lang.Object ref = etplTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        etplTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string etplTag = 2;</code>
     */
    public Builder setEtplTag(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      etplTag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string etplTag = 2;</code>
     */
    public Builder clearEtplTag() {
      
      etplTag_ = getDefaultInstance().getEtplTag();
      onChanged();
      return this;
    }
    /**
     * <code>string etplTag = 2;</code>
     */
    public Builder setEtplTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      etplTag_ = value;
      onChanged();
      return this;
    }

    private int etplOutputFormat_ = 0;
    /**
     * <code>.exporttask.WshExportFormat etplOutputFormat = 3;</code>
     */
    public int getEtplOutputFormatValue() {
      return etplOutputFormat_;
    }
    /**
     * <code>.exporttask.WshExportFormat etplOutputFormat = 3;</code>
     */
    public Builder setEtplOutputFormatValue(int value) {
      etplOutputFormat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.exporttask.WshExportFormat etplOutputFormat = 3;</code>
     */
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat getEtplOutputFormat() {
      @SuppressWarnings("deprecation")
      com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat result = com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat.valueOf(etplOutputFormat_);
      return result == null ? com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat.UNRECOGNIZED : result;
    }
    /**
     * <code>.exporttask.WshExportFormat etplOutputFormat = 3;</code>
     */
    public Builder setEtplOutputFormat(com.jw.platform.pcm.m4910.f010.microservice.WshExportFormat value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      etplOutputFormat_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.exporttask.WshExportFormat etplOutputFormat = 3;</code>
     */
    public Builder clearEtplOutputFormat() {
      
      etplOutputFormat_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object etplOutputColumns_ = "";
    /**
     * <code>string etplOutputColumns = 4;</code>
     */
    public java.lang.String getEtplOutputColumns() {
      java.lang.Object ref = etplOutputColumns_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        etplOutputColumns_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string etplOutputColumns = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEtplOutputColumnsBytes() {
      java.lang.Object ref = etplOutputColumns_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        etplOutputColumns_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string etplOutputColumns = 4;</code>
     */
    public Builder setEtplOutputColumns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      etplOutputColumns_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string etplOutputColumns = 4;</code>
     */
    public Builder clearEtplOutputColumns() {
      
      etplOutputColumns_ = getDefaultInstance().getEtplOutputColumns();
      onChanged();
      return this;
    }
    /**
     * <code>string etplOutputColumns = 4;</code>
     */
    public Builder setEtplOutputColumnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      etplOutputColumns_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object etplExpr_ = "";
    /**
     * <code>string etplExpr = 5;</code>
     */
    public java.lang.String getEtplExpr() {
      java.lang.Object ref = etplExpr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        etplExpr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string etplExpr = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEtplExprBytes() {
      java.lang.Object ref = etplExpr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        etplExpr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string etplExpr = 5;</code>
     */
    public Builder setEtplExpr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      etplExpr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string etplExpr = 5;</code>
     */
    public Builder clearEtplExpr() {
      
      etplExpr_ = getDefaultInstance().getEtplExpr();
      onChanged();
      return this;
    }
    /**
     * <code>string etplExpr = 5;</code>
     */
    public Builder setEtplExprBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      etplExpr_ = value;
      onChanged();
      return this;
    }

    private int etplId_ ;
    /**
     * <code>int32 etplId = 6;</code>
     */
    public int getEtplId() {
      return etplId_;
    }
    /**
     * <code>int32 etplId = 6;</code>
     */
    public Builder setEtplId(int value) {
      
      etplId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 etplId = 6;</code>
     */
    public Builder clearEtplId() {
      
      etplId_ = 0;
      onChanged();
      return this;
    }

    private int etplExecTimes_ ;
    /**
     * <code>int32 etplExecTimes = 7;</code>
     */
    public int getEtplExecTimes() {
      return etplExecTimes_;
    }
    /**
     * <code>int32 etplExecTimes = 7;</code>
     */
    public Builder setEtplExecTimes(int value) {
      
      etplExecTimes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 etplExecTimes = 7;</code>
     */
    public Builder clearEtplExecTimes() {
      
      etplExecTimes_ = 0;
      onChanged();
      return this;
    }

    private int etplExecOkTimes_ ;
    /**
     * <code>int32 etplExecOkTimes = 8;</code>
     */
    public int getEtplExecOkTimes() {
      return etplExecOkTimes_;
    }
    /**
     * <code>int32 etplExecOkTimes = 8;</code>
     */
    public Builder setEtplExecOkTimes(int value) {
      
      etplExecOkTimes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 etplExecOkTimes = 8;</code>
     */
    public Builder clearEtplExecOkTimes() {
      
      etplExecOkTimes_ = 0;
      onChanged();
      return this;
    }

    private int etplStatus_ ;
    /**
     * <code>int32 etplStatus = 9;</code>
     */
    public int getEtplStatus() {
      return etplStatus_;
    }
    /**
     * <code>int32 etplStatus = 9;</code>
     */
    public Builder setEtplStatus(int value) {
      
      etplStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 etplStatus = 9;</code>
     */
    public Builder clearEtplStatus() {
      
      etplStatus_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object etplCreated_ = "";
    /**
     * <code>string etplCreated = 10;</code>
     */
    public java.lang.String getEtplCreated() {
      java.lang.Object ref = etplCreated_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        etplCreated_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string etplCreated = 10;</code>
     */
    public com.google.protobuf.ByteString
        getEtplCreatedBytes() {
      java.lang.Object ref = etplCreated_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        etplCreated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string etplCreated = 10;</code>
     */
    public Builder setEtplCreated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      etplCreated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string etplCreated = 10;</code>
     */
    public Builder clearEtplCreated() {
      
      etplCreated_ = getDefaultInstance().getEtplCreated();
      onChanged();
      return this;
    }
    /**
     * <code>string etplCreated = 10;</code>
     */
    public Builder setEtplCreatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      etplCreated_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object etplUpdated_ = "";
    /**
     * <code>string etplUpdated = 11;</code>
     */
    public java.lang.String getEtplUpdated() {
      java.lang.Object ref = etplUpdated_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        etplUpdated_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string etplUpdated = 11;</code>
     */
    public com.google.protobuf.ByteString
        getEtplUpdatedBytes() {
      java.lang.Object ref = etplUpdated_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        etplUpdated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string etplUpdated = 11;</code>
     */
    public Builder setEtplUpdated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      etplUpdated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string etplUpdated = 11;</code>
     */
    public Builder clearEtplUpdated() {
      
      etplUpdated_ = getDefaultInstance().getEtplUpdated();
      onChanged();
      return this;
    }
    /**
     * <code>string etplUpdated = 11;</code>
     */
    public Builder setEtplUpdatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      etplUpdated_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object etplDeleted_ = "";
    /**
     * <code>string etplDeleted = 12;</code>
     */
    public java.lang.String getEtplDeleted() {
      java.lang.Object ref = etplDeleted_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        etplDeleted_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string etplDeleted = 12;</code>
     */
    public com.google.protobuf.ByteString
        getEtplDeletedBytes() {
      java.lang.Object ref = etplDeleted_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        etplDeleted_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string etplDeleted = 12;</code>
     */
    public Builder setEtplDeleted(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      etplDeleted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string etplDeleted = 12;</code>
     */
    public Builder clearEtplDeleted() {
      
      etplDeleted_ = getDefaultInstance().getEtplDeleted();
      onChanged();
      return this;
    }
    /**
     * <code>string etplDeleted = 12;</code>
     */
    public Builder setEtplDeletedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      etplDeleted_ = value;
      onChanged();
      return this;
    }

    private int operatorId_ ;
    /**
     * <code>int32 operatorId = 13;</code>
     */
    public int getOperatorId() {
      return operatorId_;
    }
    /**
     * <code>int32 operatorId = 13;</code>
     */
    public Builder setOperatorId(int value) {
      
      operatorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 operatorId = 13;</code>
     */
    public Builder clearOperatorId() {
      
      operatorId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:exporttask.WshExportTpl)
  }

  // @@protoc_insertion_point(class_scope:exporttask.WshExportTpl)
  private static final com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl();
  }

  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WshExportTpl>
      PARSER = new com.google.protobuf.AbstractParser<WshExportTpl>() {
    @java.lang.Override
    public WshExportTpl parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WshExportTpl(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WshExportTpl> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WshExportTpl> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

