// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/exporttask.proto

package com.jw.platform.pcm.m4910.f010.microservice;

/**
 * <pre>
 * repeated 表示数组
 * </pre>
 *
 * Protobuf type {@code exporttask.WshExportTaskListTplRes}
 */
public  final class WshExportTaskListTplRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:exporttask.WshExportTaskListTplRes)
    WshExportTaskListTplResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WshExportTaskListTplRes.newBuilder() to construct.
  private WshExportTaskListTplRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WshExportTaskListTplRes() {
    errCode_ = "";
    errMsg_ = "";
    data_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WshExportTaskListTplRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            errCode_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            errMsg_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              data_ = new java.util.ArrayList<com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl>();
              mutable_bitField0_ |= 0x00000004;
            }
            data_.add(
                input.readMessage(com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        data_ = java.util.Collections.unmodifiableList(data_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTaskListTplRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTaskListTplRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes.class, com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes.Builder.class);
  }

  private int bitField0_;
  public static final int ERRCODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object errCode_;
  /**
   * <code>string errCode = 1;</code>
   */
  public java.lang.String getErrCode() {
    java.lang.Object ref = errCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errCode_ = s;
      return s;
    }
  }
  /**
   * <code>string errCode = 1;</code>
   */
  public com.google.protobuf.ByteString
      getErrCodeBytes() {
    java.lang.Object ref = errCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERRMSG_FIELD_NUMBER = 2;
  private volatile java.lang.Object errMsg_;
  /**
   * <code>string errMsg = 2;</code>
   */
  public java.lang.String getErrMsg() {
    java.lang.Object ref = errMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string errMsg = 2;</code>
   */
  public com.google.protobuf.ByteString
      getErrMsgBytes() {
    java.lang.Object ref = errMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private java.util.List<com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl> data_;
  /**
   * <code>repeated .exporttask.WshExportTpl data = 3;</code>
   */
  public java.util.List<com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl> getDataList() {
    return data_;
  }
  /**
   * <code>repeated .exporttask.WshExportTpl data = 3;</code>
   */
  public java.util.List<? extends com.jw.platform.pcm.m4910.f010.microservice.WshExportTplOrBuilder> 
      getDataOrBuilderList() {
    return data_;
  }
  /**
   * <code>repeated .exporttask.WshExportTpl data = 3;</code>
   */
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <code>repeated .exporttask.WshExportTpl data = 3;</code>
   */
  public com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl getData(int index) {
    return data_.get(index);
  }
  /**
   * <code>repeated .exporttask.WshExportTpl data = 3;</code>
   */
  public com.jw.platform.pcm.m4910.f010.microservice.WshExportTplOrBuilder getDataOrBuilder(
      int index) {
    return data_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getErrCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errCode_);
    }
    if (!getErrMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errMsg_);
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeMessage(3, data_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getErrCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errCode_);
    }
    if (!getErrMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errMsg_);
    }
    for (int i = 0; i < data_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, data_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes)) {
      return super.equals(obj);
    }
    com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes other = (com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes) obj;

    boolean result = true;
    result = result && getErrCode()
        .equals(other.getErrCode());
    result = result && getErrMsg()
        .equals(other.getErrMsg());
    result = result && getDataList()
        .equals(other.getDataList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
    hash = (53 * hash) + getErrCode().hashCode();
    hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
    hash = (53 * hash) + getErrMsg().hashCode();
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * repeated 表示数组
   * </pre>
   *
   * Protobuf type {@code exporttask.WshExportTaskListTplRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exporttask.WshExportTaskListTplRes)
      com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTaskListTplRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTaskListTplRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes.class, com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes.Builder.class);
    }

    // Construct using com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      errCode_ = "";

      errMsg_ = "";

      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        dataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskProto.internal_static_exporttask_WshExportTaskListTplRes_descriptor;
    }

    @java.lang.Override
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes getDefaultInstanceForType() {
      return com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes.getDefaultInstance();
    }

    @java.lang.Override
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes build() {
      com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes buildPartial() {
      com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes result = new com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.errCode_ = errCode_;
      result.errMsg_ = errMsg_;
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes) {
        return mergeFrom((com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes other) {
      if (other == com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes.getDefaultInstance()) return this;
      if (!other.getErrCode().isEmpty()) {
        errCode_ = other.errCode_;
        onChanged();
      }
      if (!other.getErrMsg().isEmpty()) {
        errMsg_ = other.errMsg_;
        onChanged();
      }
      if (dataBuilder_ == null) {
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
      } else {
        if (!other.data_.isEmpty()) {
          if (dataBuilder_.isEmpty()) {
            dataBuilder_.dispose();
            dataBuilder_ = null;
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
            dataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDataFieldBuilder() : null;
          } else {
            dataBuilder_.addAllMessages(other.data_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object errCode_ = "";
    /**
     * <code>string errCode = 1;</code>
     */
    public java.lang.String getErrCode() {
      java.lang.Object ref = errCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string errCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getErrCodeBytes() {
      java.lang.Object ref = errCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errCode = 1;</code>
     */
    public Builder setErrCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string errCode = 1;</code>
     */
    public Builder clearErrCode() {
      
      errCode_ = getDefaultInstance().getErrCode();
      onChanged();
      return this;
    }
    /**
     * <code>string errCode = 1;</code>
     */
    public Builder setErrCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object errMsg_ = "";
    /**
     * <code>string errMsg = 2;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string errMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errMsg = 2;</code>
     */
    public Builder setErrMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string errMsg = 2;</code>
     */
    public Builder clearErrMsg() {
      
      errMsg_ = getDefaultInstance().getErrMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string errMsg = 2;</code>
     */
    public Builder setErrMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errMsg_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl> data_ =
      java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        data_ = new java.util.ArrayList<com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl>(data_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl, com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.Builder, com.jw.platform.pcm.m4910.f010.microservice.WshExportTplOrBuilder> dataBuilder_;

    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public java.util.List<com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl> getDataList() {
      if (dataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(data_);
      } else {
        return dataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public int getDataCount() {
      if (dataBuilder_ == null) {
        return data_.size();
      } else {
        return dataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl getData(int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);
      } else {
        return dataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public Builder setData(
        int index, com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
      } else {
        dataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public Builder setData(
        int index, com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public Builder addData(com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
      } else {
        dataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public Builder addData(
        int index, com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(index, value);
        onChanged();
      } else {
        dataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public Builder addData(
        com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public Builder addData(
        int index, com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl> values) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
      } else {
        dataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public Builder removeData(int index) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.remove(index);
        onChanged();
      } else {
        dataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.Builder getDataBuilder(
        int index) {
      return getDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTplOrBuilder getDataOrBuilder(
        int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);  } else {
        return dataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public java.util.List<? extends com.jw.platform.pcm.m4910.f010.microservice.WshExportTplOrBuilder> 
         getDataOrBuilderList() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(data_);
      }
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.Builder addDataBuilder() {
      return getDataFieldBuilder().addBuilder(
          com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.getDefaultInstance());
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.Builder addDataBuilder(
        int index) {
      return getDataFieldBuilder().addBuilder(
          index, com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.getDefaultInstance());
    }
    /**
     * <code>repeated .exporttask.WshExportTpl data = 3;</code>
     */
    public java.util.List<com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.Builder> 
         getDataBuilderList() {
      return getDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl, com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.Builder, com.jw.platform.pcm.m4910.f010.microservice.WshExportTplOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl, com.jw.platform.pcm.m4910.f010.microservice.WshExportTpl.Builder, com.jw.platform.pcm.m4910.f010.microservice.WshExportTplOrBuilder>(
                data_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:exporttask.WshExportTaskListTplRes)
  }

  // @@protoc_insertion_point(class_scope:exporttask.WshExportTaskListTplRes)
  private static final com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes();
  }

  public static com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WshExportTaskListTplRes>
      PARSER = new com.google.protobuf.AbstractParser<WshExportTaskListTplRes>() {
    @java.lang.Override
    public WshExportTaskListTplRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WshExportTaskListTplRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WshExportTaskListTplRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WshExportTaskListTplRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.jw.platform.pcm.m4910.f010.microservice.WshExportTaskListTplRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

