// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/exporttask.proto

package com.jw.platform.pcm.m4910.f010.microservice;

public interface WshExportTaskListTplReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exporttask.WshExportTaskListTplReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 etplId = 1;</code>
   */
  int getEtplId();

  /**
   * <code>string etplName = 2;</code>
   */
  java.lang.String getEtplName();
  /**
   * <code>string etplName = 2;</code>
   */
  com.google.protobuf.ByteString
      getEtplNameBytes();

  /**
   * <code>string etplTag = 3;</code>
   */
  java.lang.String getEtplTag();
  /**
   * <code>string etplTag = 3;</code>
   */
  com.google.protobuf.ByteString
      getEtplTagBytes();
}
