server:
  port: 8080
spring:
  application:
    name: 4100000G

spring:
  cloud:
    gateway:
      routes:
      - id: 163_route
        uri: http://www.163.com/
        predicates:
        - Path=/163