server:
  port: 14911
  servlet:
    context-path: /4910010RA
grpc:
  client:
    boot-4910010R:
      host:
      - ${LOCAL-GRPC-HOST:127.0.0.1}
      port:
      - 24910
      enableKeepAlive: true
      keepAliveWithoutCalls: true