grpc:
  client:
    boot-4910010R:
#      host:
#      - ${LOCAL-GRPC-HOST:127.0.0.1}
#      port:
#      - 24910
      address: static://localhost:24910
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext